apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-com-local-bootstrapper-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
data:
  ENV: "prd"
  ACCOUNT_AVATARS_CONTAINER_NAME: "account-avatars-prd"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1.kafka-platform.svc.cluster.local:19092"
  KAFKA_COCKTAILS_TOPIC_DEFS: "cocktails-update-topic-prd,cocktails-ingestion-extraction-results-prd,cocktails-ingestion-chunking-results-prd"
  KAFKA_DEFAULT_TOPIC_PARTITIONS: "4"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  COSMOSDB_ACCOUNT_ENDPOINT: "https://cosmosdb.azure-platform.svc.cluster.local:8081/"
  COSMOSDB_ENABLE_ENDPOINT_DISCOVERY: "false"
  COSMOSDB_COCKTAILS_DATABASE_NAME: "cocktails-db-prd"
  COSMOSDB_COCKTAILS_CONTAINER_DEFS: "cezzis-cocktails-cocktail:/id,cezzis-cocktails-ingredient:/id,cezzis-device-auth:/id"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.openobserve-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cezzis-com-bootstrapper"
  OTEL_SERVICE_NAMESPACE: "cezzis"
  RABBITMQ_VHOST: "cezzis-prd"
  RABBITMQ_HOST: "http://rabbitmq.rabbitmq-platform.svc.cluster.local"
  RABBITMQ_ADMIN_PORT: "15672"
  RABBITMQ_ADMIN_USERNAME: "admin"
  RABBITMQ_APP_USERNAME: "cezzis-app-user-prd"
  RABBITMQ_APP_CONFIG_FILE_PATH: "/config/rabbitmq.json"
  QDRANT_HOST: "qdrant.ai-platform.svc.cluster.local"
  QDRANT_PORT: "6333"
  QDRANT_API_KEY: ""
  QDRANT_COLLECTION_NAME: "cocktails-prd"
  QDRANT_VECTOR_SIZE: "768"
  QDRANT_USE_HTTPS: "false"