apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cocktails-bootstrapper-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cocktails-bootstrapper-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AZURE_STORAGE_CONNECTION_STRING: "DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey={{ .storageAccountKey }};BlobEndpoint=http://azurite.azure-platform.svc.cluster.local:10000/devstoreaccount1;"
  data:
    - secretKey: storageAccountKey
      remoteRef:
        key: cezzis-blob-storage-access-key-onprem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cocktails-bootstrapper-shared-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cocktails-bootstrapper-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTEL_OTLP_AUTH_HEADER: "Bearer {{ .otelApiKey }}"
        RABBITMQ_APP_PASSWORD: "{{ .rabbitmqAppPassword }}"
        RABBITMQ_ADMIN_PASSWORD: "{{ .rabbitmqAdminPassword }}"
        COSMOSDB_ACCOUNT_KEY: "{{ .cosmosDbAccountKey }}"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-api-key-onprem
    - secretKey: rabbitmqAdminPassword
      remoteRef:
        key: rabbitmq-admin-password-onprem
    - secretKey: rabbitmqAppPassword
      remoteRef:
        key: rabbitmq-app-password-onprem
    - secretKey: cosmosDbAccountKey
      remoteRef:
        key: azure-cosmosdb-account-key-onprem
