apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - configmap.yml
  - external-secrets.yml
  - rabbitmq-configmap.yml
  - job.yml
images:
  - name: acrveceusgloshared001.azurecr.io/cezziscombootstrapper
    newTag: 0.0.80
    newName: acrveceusgloshared001.azurecr.io/cezziscombootstrapper
