apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
data:
  rabbitmq.json: |
    {
        "exchanges": [
            {
                "name": "cocktail-user-actions-topic",
                "type": "topic",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
            },
            {
                "name": "account-updates-topic",
                "type": "topic",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
            },
            {
                "name": "cocktail-updates-topic",
                "type": "topic",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
            },
            {
                "name": "cocktail-updates-schedule-topic",
                "type": "topic",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
            },
            {
                "name": "deadletter-topic",
                "type": "topic",
                "durable": true,
                "auto_delete": false,
                "internal": false,
                "arguments": {}
            }
        ],
        "queues": [
            {
                "name": "cocktail-ratings-sync-queue",
                "arguments": {}
            },
            {
                "name": "cocktail-ratings-sync-queue-dlx",
                "arguments": {}
            },
            {
                "name": "idp-account-profile-sync-queue",
                "arguments": {}
            },
            {
                "name": "idp-account-profile-sync-queue-dlx",
                "arguments": {}
            },
            {
                "name": "idp-account-password-sync-queue",
                "arguments": {}
            },
            {
                "name": "idp-account-password-sync-queue-dlx",
                "arguments": {}
            },
            {
                "name": "zoho-email-dispatch-queue",
                "arguments": {}
            },
            {
                "name": "zoho-email-dispatch-queue-dlx",
                "arguments": {}
            },
            {
                "name": "cocktail-updates-queue",
                "arguments": {}
            },
            {
                "name": "cocktail-updates-queue-dlx",
                "arguments": {}
            },
            {
                "name": "cocktail-updates-scheduled-queue",
                "arguments": {}
            },
            {
                "name": "cocktail-updates-scheduled-queue-dlx",
                "arguments": {}
            },
            {
                "name": "accounts-sync-cocktail-updates-queue",
                "arguments": {}
            },
            {
                "name": "accounts-sync-cocktail-updates-queue-dlx",
                "arguments": {}
            }
        ],
        "bindings": [
            {
                "source": "cocktail-user-actions-topic",
                "destination": "cocktail-ratings-sync-queue",
                "destination_type": "queue",
                "routing_key": "cocktail.*.rated",
                "arguments": {}
            },
            {
                "source": "cocktail-user-actions-topic",
                "destination": "zoho-email-dispatch-queue",
                "destination_type": "queue",
                "routing_key": "cocktail.*.email",
                "arguments": {}
            },
            {
                "source": "account-updates-topic",
                "destination": "idp-account-profile-sync-queue",
                "destination_type": "queue",
                "routing_key": "account.owned.profile.updated",
                "arguments": {}
            },
            {
                "source": "account-updates-topic",
                "destination": "idp-account-password-sync-queue",
                "destination_type": "queue",
                "routing_key": "account.owned.password.updated",
                "arguments": {}
            },
            {
                "source": "cocktail-updates-topic",
                "destination": "cocktail-updates-queue",
                "destination_type": "queue",
                "routing_key": "cocktail.*.updated",
                "arguments": {}
            },
            {
                "source": "cocktail-updates-topic",
                "destination": "accounts-sync-cocktail-updates-queue",
                "destination_type": "queue",
                "routing_key": "cocktail.*.updated",
                "arguments": {}
            },
            {
                "source": "cocktail-updates-schedule-topic",
                "destination": "cocktail-updates-scheduled-queue",
                "destination_type": "queue",
                "routing_key": "cocktail.*.updated-scheduled",
                "arguments": {}
            },
            {
                "source": "deadletter-topic",
                "destination": "cocktail-ratings-sync-queue-dlx",
                "destination_type": "queue",
                "routing_key": "cocktail.*.rated",
                "arguments": {}
            },
            {
                "source": "deadletter-topic",
                "destination": "zoho-email-dispatch-queue-dlx",
                "destination_type": "queue",
                "routing_key": "cocktail.*.email",
                "arguments": {}
            },
            {
                "source": "deadletter-topic",
                "destination": "idp-account-profile-sync-queue-dlx",
                "destination_type": "queue",
                "routing_key": "account.owned.profile.updated",
                "arguments": {}
            },
            {
                "source": "deadletter-topic",
                "destination": "idp-account-password-sync-queue-dlx",
                "destination_type": "queue",
                "routing_key": "account.owned.password.updated",
                "arguments": {}
            },
            {
                "source": "deadletter-topic",
                "destination": "cocktail-updates-queue-dlx",
                "destination_type": "queue",
                "routing_key": "cocktail.*.updated",
                "arguments": {}
            },
            {
                "source": "deadletter-topic",
                "destination": "accounts-sync-cocktail-updates-queue-dlx",
                "destination_type": "queue",
                "routing_key": "accounts.cocktail.*.updated",
                "arguments": {}
            }
        ]
    }