apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cezzis-com-local-bootstrapper
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: bootstrapper=acrveceusgloshared001.azurecr.io/cezziscombootstrapper
    argocd-image-updater.argoproj.io/bootstrapper.kustomize.image-name: acrveceusgloshared001.azurecr.io/cezziscombootstrapper
    argocd-image-updater.argoproj.io/bootstrapper.update-strategy: semver
    argocd-image-updater.argoproj.io/bootstrapper.semver-constraint: "v0.x"
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mtnvencenzo/cezzis-com-local-bootstrapper.git'
    targetRevision: main
    path: .iac/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: cezzis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true