apiVersion: v1
kind: ConfigMap
metadata:
  name: cezzis-com-local-bootstrapper-cloudsync-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
data:
  ENV: "prd"
  ENABLE_RABBITMQ: "false"
  ENABLE_BLOB_STORAGE: "false"
  ENABLE_KAFKA: "true"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-broker-1.kafka-platform.svc.cluster.local:19092,kafka-broker-2.kafka-platform.svc.cluster.local:19093,kafka-broker-3.kafka-platform.svc.cluster.local:19095"
  KAFKA_COCKTAILS_TOPIC_DEFS: "cocktails-update-topic-cloudsync,cocktails-ingestion-extraction-results-cloudsync,cocktails-ingestion-chunking-results-cloudsync"
  KAFKA_DEFAULT_TOPIC_PARTITIONS: "4"
  KAFKA_SECURITY_PROTOCOL: "PLAINTEXT"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.elastic-platform.svc.cluster.local:4318"
  OTEL_SERVICE_NAME: "cezzis-com-bootstrapper-cloudsync"
  OTEL_SERVICE_NAMESPACE: "cezzis"
